name: news_app
description: News app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.6.0
  json_annotation: ^4.9.0
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sizer: ^3.1.3
  intl: ^0.20.2
  get_it: ^9.2.0
  connectivity_plus: ^7.0.0
  shimmer: ^3.0.0
  go_router: ^17.0.1
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/newspaper.jpg