name: personal_finance_tracker
description: A simple Flutter app for tracking personal finances.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sizer: ^3.1.3
  intl: ^0.20.2
  flutter_material_color_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true